# Project Basic Settings (Please modify this section according to your project requirements)
title: "Padavan ng CAKE Linux 3.4"
description: "Padavan-NG"
url: "https://diablomike20.github.io"
baseurl: "/padavan-ng"
github_url: "https://github.com/diablomike20/padavan-ng"

# Force GFM engine to start and automatically generate IDs (to ensure TOC single-page redirection works perfectly)
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
